service: channel-status-notifier

custom:
  serverless-offline-sns:
    port: 4002 # a free port for the sns server to run on
    debug: false
  mySnsTopic: "${self:service}-${self:provider.stage}-sns-consume"
  mySnsTopicArn:
    local: "arn:aws:sns:us-east-1:123456789012:${self:custom.mySnsTopic}"
    dev:
      {
        "Fn::Join":
          [
            "",
            [
              "arn:aws:sns:${self:provider.region}:",
              { "Ref": "AWS::AccountId" },
              ":${self:custom.mySnsTopic}",
            ],
          ],
      }
    prod:
      {
        "Fn::Join":
          [
            "",
            [
              "arn:aws:sns:${self:provider.region}:",
              { "Ref": "AWS::AccountId" },
              ":${self:custom.mySnsTopic}",
            ],
          ],
      }

provider:
  name: aws
  role: arn:aws:iam::807711422928:role/FTApplicationRoleFor_channel-status-notifier
  runtime: nodejs12.x
  timeout: 30
  memorySize: 3008
  profile: csn
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  stackTags:
    teamDL: ftlabs@ft.com
    environment: p
    systemCode: channel-status-notifier
  environment:
    NODE_ENV: "${file(./serverless.env.yml):NODE_ENV}"
    SLACK_TOKEN: "${file(./serverless.env.yml):SLACK_TOKEN}"

plugins:
  - serverless-offline
  - serverless-step-functions
  - serverless-offline-sns

tags:
  teamDL: ftlabs@ft.com
  environment: p
  systemCode: channel-status-notifier

functions:
  post:
    handler: post.post
    events:
      - sns: ${self:custom.mySnsTopic}

  trigger:
    handler: trigger.trigger
    events:
      - http:
          path: handler
          method: any
    environment:
      mySnsTopicArn: ${self:custom.mySnsTopicArn.${self:provider.stage}}
